name: Build & Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      trigger:
        description: "start manually"
        required: true
        default: "yes"

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Debug - Check files
        run: ls -R .devcontainer

      - name: Set DATE_TAG
        run: echo "DATE_TAG=$(date +%Y%m%d-%H%M)" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/emblincram/devcon:latest \
                      -t ghcr.io/emblincram/devcon:$DATE_TAG \
                      -f .devcontainer/Dockerfile .
      
      - name: Push Docker Image
        run: |
          docker push ghcr.io/emblincram/devcon:latest
          docker push ghcr.io/emblincram/devcon:$DATE_TAG
